### ISSUE TITLE
站内信息单行过长时超出边界

### ISSUE THREAD

**Issue by MeiK-h** [sdutacm/onlinejudge3-issues#14]
**问题描述**
当站内信单行过长时会超出边界

**复现步骤**
![image](https://user-images.githubusercontent.com/20951666/51888320-aed76700-23d1-11e9-8e9b-24360075c239.png)

**期望表现**
换行显示

**系统信息**
 - 操作系统：Ubuntu
 - 浏览器：Chrome
 -  浏览器版本：版本 71.0.3578.98（正式版本） （64 位）

**Comment by dreamerblue** [comment]
3.0.0.201902110 fixed.
