### ISSUE TITLE
能否使用不同的颜色标示不同的结果

### ISSUE THREAD

**Issue by MeiK-h** [sdutacm/onlinejudge3-issues#15]
如图，现在统一用红色表示错误感觉没有区分度，也失去了一些乐趣。（比如“黄了十五发，我终于绿了！”）

![image](https://user-images.githubusercontent.com/20951666/52544769-e7be0580-2ded-11e9-8995-6b6eced39741.png)
![image](https://user-images.githubusercontent.com/20951666/52544779-f3a9c780-2ded-11e9-9ccb-cbfd523b32da.png)

**Comment by dreamerblue** [comment]
色彩设置已有相关实现，当前版本暂未开放，请等待后续版本。

**Comment by dreamerblue** [comment]
v3.0.0.201902180 f8a41f84f46ec80c88d33d761ba6508b2f7e0c06
