### ISSUE TITLE
为什么首页上不能直接进入 Solutions 页面？

### ISSUE THREAD

**Issue by MeiK2333** [sdutacm/onlinejudge3-issues#16]
看 Solutions 还需要点进一个状态页面然后 `Clear`，为啥不直接在首页加一个链接呢？

![image](https://user-images.githubusercontent.com/20951666/52544873-89455700-2dee-11e9-9b64-9720d9d44de1.png)

**Comment by dreamerblue** [comment]
这个是有意地弱化 Solutions，力求只在用户需要查询时题目提交记录和个人提交记录时使用，不希望给过高的展示优先级。

**Comment by dreamerblue** [comment]
可以考虑开启 Pro Mode。
