### ISSUE TITLE
样例和代码复制粘贴过来会有空行的问题

### ISSUE THREAD

**Issue by 18110581023** [sdutacm/onlinejudge3-issues#17]
样例粘到终端后，每一行之间有空行，有时候会有不便之处。
还有代码粘过来也是每一行之间有空行，总得一行一行去删。
不知道这个问题是否能通过技术手段解决掉呢，没解决掉也没关系，只是体验略差而已

**Comment by dreamerblue** [comment]
用户浏览器问题，已联系解决。close 了。
