### ISSUE TITLE
关于问题链接页数和输入复制的问题

### ISSUE THREAD

**Issue by Funesoul** [sdutacm/onlinejudge3-issues#19]
首先说问题链接页数的建议。希望能把显示方式改成OJ2那样会自动拓展而不是需要手动翻页。
然后是输入复制。复制到粘贴板的输入例子会自动添加一行换行，如果不是无限循环会导致结果输出后立刻关闭弹窗，必须手动去除换行符，十分不方便。

**Comment by dreamerblue** [comment]
@Funesoul 首先感谢关注 OnlineJudge 3。

对于你的建议的回复：
1. 「希望能把显示方式改成OJ2那样会自动拓展而不是需要手动翻页」这点没有理解是什么意思，请具体描述下是哪个页面。
2. 问题未复现，请提供下具体的题号，以及你的操作系统和使用的 IDE。

**Comment by Funesoul** [comment]
1。好像每个页面都是这样吧。主要是contest和problem有些影响。每个页面只显示二十个问题。
2.遇到过很多次。最近的问题是并查集：小雷的茶几。win10，CB。把复制的例子粘贴到文本文档会看到多了一个换行符

**Comment by dreamerblue** [comment]
1. OJ2 也需要手动翻页的哦。你的意思应该是想要每一页显示的条数多一些吧。这个已有支持设置每页条数的开发规划。
2. 问题未复现。对 CMD 来说，示例加空行只是为了方便用户，不需要再按一次回车才能看到最后一组的输出。粘贴后会停留在如下图界面，还需要按一次任意键才会关闭窗口。

![image](https://user-images.githubusercontent.com/19774268/74425771-31bd4980-4e8f-11ea-9c98-d7f1b7000051.png)

**Comment by Funesoul** [comment]
2.我的意思是除了那一行还会有一行。。。
整了张图
![121111](https://user-images.githubusercontent.com/40417061/74445329-2da22380-4eb1-11ea-8897-0ea63c71555f.gif)

**Comment by Funesoul** [comment]
我刚刚猜测也可能是我写的代码的问题。但抄了一份网上的发现还是一样。。。

**Comment by dreamerblue** [comment]
你这种每一行都自动被加了一行空行的情况我这没办法复现。建议试试粘贴到一些纯文本编辑器（不会自动格式化的编辑器）里看看复制的内容是否符合预期。

如果还有疑问，建议可以在 OJ 下方点击 Join Discussion 加入群聊，沟通更方便。

**Comment by Funesoul** [comment]
粘贴到CMD里也是这样的。我也不知道为什么。
就算是手动复制也会出现相同的情况。
好吧

**Comment by dreamerblue** [comment]
好吧，那就不是复制按钮逻辑的问题了。可以考虑排查下系统上哪些地方复制会出问题，以及是否有开启什么插件会辅助格式化。
