### ISSUE TITLE
Contest 显示不了ID

### ISSUE THREAD

**Issue by 18110581023** [sdutacm/onlinejudge3-issues#2]
**问题描述**
Contest显示不了ID，就四位数的那个

**复现步骤**
请描述问题复现的步骤
1. 步骤 1
2. 步骤 2
3. 步骤 3...

**期望表现**

**系统信息**
 - 操作系统： Windows 10
 - 浏览器：Microsoft Edge
 -  浏览器版本：

**Comment by dreamerblue** [comment]
问题已记录，目前出于简化信息的初衷去掉了部分的 ID 展示，我们后续会考虑如何在需要的情况下展示 ID。

**Comment by dreamerblue** [comment]
可以再设置中打开 Pro Mode 来查看 ID。
