### ISSUE TITLE
不能注册

### ISSUE THREAD

**Issue by Fenhanpi** [sdutacm/onlinejudge3-issues#21]
![QQ截图20200523233302](https://user-images.githubusercontent.com/65821672/82734472-c6b4c600-9d4d-11ea-9062-bc7f24dd8704.png)

**Comment by dreamerblue** [comment]
你好，我这边没法复现问题。请提供下完整的复现步骤。

**Comment by Fenhanpi** [comment]
https://acm.sdut.edu.cn/onlinejudge3/这个网站没法注册

**Comment by dreamerblue** [comment]
@Fenhanpi 你这样说谁也没法复现问题呀，请提供下完整的复现步骤。

例如：
1. 点击右上角 Join
2. 切换 Register
3. 填写完毕全部表单，点击提交后弹出 xx 错误
