### ISSUE TITLE
状态页面无法查看 1000 页之后的内容

### ISSUE THREAD

**Issue by MeiK2333** [sdutacm/onlinejudge3-issues#3]
**问题描述**

状态页面，无法查看 1000 页之后的内容

**复现步骤**
无需步骤

**期望表现**
可以顺序查看

**系统信息**
 - 操作系统：Ubuntu 18.04
 - 浏览器：Chrome
 -  浏览器版本：None

**Comment by dreamerblue** [comment]
marked.

**Comment by dreamerblue** [comment]
已实现 @3.4.0
