### ISSUE TITLE
对于上传文件的类型没有做实际的验证

### ISSUE THREAD

**Issue by MeiK-h** [sdutacm/onlinejudge3-issues#4]
**问题描述**
虽然限制了上传文件的后缀只能为 jpg、png 等，但是服务器端没有做验证，导致可以传其他文件上去。

**复现步骤**
1. 修改一个文件的后缀名为 jpg
2. 在个人页面上传

**期望表现**
报错，实际上传成功，可以参照 [MeiK](https://acm.sdut.edu.cn/onlinejudge3_beta/users/21060) 的个人页面

**系统信息**
系统无关

**Comment by QAQrz** [comment]
Fixed
